services:
  env-dashboard:
    image: "mcr.microsoft.com/dotnet/nightly/aspire-dashboard:latest"
    ports:
      - "18888"
    expose:
      - "18889"
      - "18890"
    networks:
      - "aspire"
    restart: "always"
  umbraco-db:
    image: "${UMBRACO_DB_IMAGE}"
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "${DB_PASSWORD}"
    ports:
      - "1433:1433"
      - "1434:1434"
    expose:
      - "1433"
    volumes:
      - type: "volume"
        target: "/var/opt/mssql"
        source: "umb_database"
        read_only: false
    networks:
      - "aspire"
    healthcheck:
      test:
        - "CMD"
        - "bash"
        - "/healthcheck.sh"
      interval: "5m"
      timeout: "5s"
      retries: 3
      start_period: "30s"
  umbraco-cms:
    image: "${UMBRACO_CMS_IMAGE}"
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      ASPNETCORE_URLS: "http://+:8080;https://+:8081"
      ASPNETCORE_Kestrel__Certificates__Default__Path: "/https/aspnetcore.pfx"
      ASPNETCORE_Kestrel__Certificates__Default__Password: "DevOnlyPassword"
      ConnectionStrings__umbracoDbDSN: "Server=umbraco-db,1433;User ID=sa;Password=${DB_PASSWORD};TrustServerCertificate=true"
      ConnectionStrings__umbracoDbDSN_ProviderName: "Microsoft.Data.SqlClient"
    ports:
      - "8081"
    volumes:
      - type: "bind"
        target: "/app/wwwroot/media"
        source: "${UMBRACO_CMS_BINDMOUNT_0}"
        read_only: false
      - type: "bind"
        target: "/app/wwwroot/scripts"
        source: "${UMBRACO_CMS_BINDMOUNT_1}"
        read_only: false
      - type: "bind"
        target: "/app/wwwroot/css"
        source: "${UMBRACO_CMS_BINDMOUNT_2}"
        read_only: false
      - type: "bind"
        target: "/app/Views"
        source: "${UMBRACO_CMS_BINDMOUNT_3}"
        read_only: false
      - type: "bind"
        target: "/app/umbraco/models"
        source: "${UMBRACO_CMS_BINDMOUNT_4}"
        read_only: false
      - type: "volume"
        target: "/app/umbraco/Logs"
        source: "umb_logs"
        read_only: false
      - type: "volume"
        target: "/app/umbraco/Data"
        source: "umb_data"
        read_only: false
    depends_on:
      umbraco-db:
        condition: "service_healthy"
    networks:
      - "aspire"
    healthcheck:
      test:
        - "CMD"
        - "curl"
        - "-f"
        - "https://+8081:/umbraco/api/health/ready"
      interval: "10s"
      timeout: "5s"
      retries: 3
      start_period: "30s"
networks:
  aspire:
    driver: "bridge"
volumes:
  umb_database:
    driver: "local"
  umb_logs:
    driver: "local"
  umb_data:
    driver: "local"
