// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from "./client";
import { client } from "./client.gen";
import type {
  BookingActionRequestModel,
  BookingData,
  BookingErrors,
  BookingResponseModel,
  BookingResponses,
  EventData,
  EventErrors,
  EventResponses,
  GetBookingDataById,
  PhotoPackageData,
  PhotoPackageErrors,
  PhotoPackageResponses,
  WhatsMyNameData,
  WhatsMyNameErrors,
  WhatsMyNameResponses,
  WhatsTheTimeMrWolfData,
  WhatsTheTimeMrWolfErrors,
  WhatsTheTimeMrWolfResponses,
  WhoAmIData,
  WhoAmIErrors,
  WhoAmIResponses,
} from "./types.gen";

export type Options<
  TData extends TDataShape = TDataShape,
  ThrowOnError extends boolean = boolean,
> = Options2<TData, ThrowOnError> & {
  /**
   * You can provide a client instance returned by `createClient()` instead of
   * individual options. This might be also useful if you want to implement a
   * custom client.
   */
  client?: Client;
  /**
   * You can pass arbitrary values through the `meta` object. This can be
   * used to access values that aren't defined as part of the SDK function.
   */
  meta?: Record<string, unknown>;
};

export class UmbracoExtensionService {
  public static GetAllPhotoPackages<ThrowOnError extends boolean = false>(
    options?: Options<PhotoPackageData, ThrowOnError>,
  ) {
    return (options?.client ?? client).get<
      PhotoPackageResponses,
      PhotoPackageErrors,
      ThrowOnError
    >({
      security: [
        {
          scheme: "bearer",
          type: "http",
        },
      ],
      url: "/umbraco/umbracoextension/api/v1/photopackages",
      ...options,
    });
  }

  public static CreatePhotoPackage<ThrowOnError extends boolean = false>(
    options?: Options<PhotoPackageData, ThrowOnError>,
  ) {
    return (options?.client ?? client).post<
      PhotoPackageResponses,
      PhotoPackageErrors,
      ThrowOnError
    >({
      security: [
        {
          scheme: "bearer",
          type: "http",
        },
      ],
      url: "/umbraco/umbracoextension/api/v1/photopackages",
      ...options,
    });
  }

  public static CreateEventType<ThrowOnError extends boolean = false>(
    options?: Options<EventData, ThrowOnError>,
  ) {
    return (options?.client ?? client).post<
      EventResponses,
      EventErrors,
      ThrowOnError
    >({
      security: [
        {
          scheme: "bearer",
          type: "http",
        },
      ],
      url: "/umbraco/umbracoextension/api/v1/eventtypes",
      ...options,
    });
  }

  public static GetEventTypes<ThrowOnError extends boolean = false>(
    options?: Options<EventData, ThrowOnError>,
  ) {
    return (options?.client ?? client).get<
      EventResponses,
      EventErrors,
      ThrowOnError
    >({
      security: [
        {
          scheme: "bearer",
          type: "http",
        },
      ],
      url: "/umbraco/umbracoextension/api/v1/eventtypes",
      ...options,
    });
  }

  public static CreateBooking<ThrowOnError extends boolean = false>(
    options?: Options<BookingData, ThrowOnError>,
  ) {
    return (options?.client ?? client).post<
      BookingResponseModel,
      BookingErrors,
      ThrowOnError
    >({
      security: [
        {
          scheme: "bearer",
          type: "http",
        },
      ],
        url: "/umbraco/umbracoextension/api/v1/bookings",
      ...options,
    });
  }

  public static ChangeBookingStatus<ThrowOnError extends boolean = false>(
    options?: Options<GetBookingDataById, ThrowOnError>,
  ) {
    return (options?.client ?? client).put<
      BookingActionRequestModel,
      BookingErrors,
      ThrowOnError
    >({
      security: [
        {
          scheme: "bearer",
          type: "http",
        },
      ],
        url: "/umbraco/umbracoextension/api/v1/bookings/{bookingId}/{action}",
      ...options,
    });
  }

  public static GetBookings<ThrowOnError extends boolean = false>(
    options?: Options<BookingData, ThrowOnError>,
  ) {
    return (options?.client ?? client).get<
      BookingResponses,
      BookingErrors,
      ThrowOnError
    >({
      security: [
        {
          scheme: "bearer",
          type: "http",
        },
      ],
        url: "/umbraco/umbracoextension/api/v1/bookings",
      ...options,
    });
  }

  public static whatsMyName<ThrowOnError extends boolean = false>(
    options?: Options<WhatsMyNameData, ThrowOnError>,
  ) {
    return (options?.client ?? client).get<
      WhatsMyNameResponses,
      WhatsMyNameErrors,
      ThrowOnError
    >({
      security: [
        {
          scheme: "bearer",
          type: "http",
        },
      ],
      url: "/umbraco/umbracoextension/api/v1/whatsMyName",
      ...options,
    });
  }

  public static whatsTheTimeMrWolf<ThrowOnError extends boolean = false>(
    options?: Options<WhatsTheTimeMrWolfData, ThrowOnError>,
  ) {
    return (options?.client ?? client).get<
      WhatsTheTimeMrWolfResponses,
      WhatsTheTimeMrWolfErrors,
      ThrowOnError
    >({
      security: [
        {
          scheme: "bearer",
          type: "http",
        },
      ],
      url: "/umbraco/umbracoextension/api/v1/whatsTheTimeMrWolf",
      ...options,
    });
  }

  public static whoAmI<ThrowOnError extends boolean = false>(
    options?: Options<WhoAmIData, ThrowOnError>,
  ) {
    return (options?.client ?? client).get<
      WhoAmIResponses,
      WhoAmIErrors,
      ThrowOnError
    >({
      security: [
        {
          scheme: "bearer",
          type: "http",
        },
      ],
      url: "/umbraco/umbracoextension/api/v1/whoAmI",
      ...options,
    });
  }
}
